### ISSUE TITLE
Empty Styles as Placholders

### ISSUE THREAD

**Issue by j** [stitchesjs/stitches#1002]
I'm trying to create a composable theme system for an internal project and target children elements without hard coding a class name.

I'd like to be able to do:

```typescript
const Headline = styled('div');
const Tagline = styled('div');
const Container = styled('div', {
  // base styles
  variants: {
    style: {
      box: {
        [`& ${Headline}`]: {
          // .. Headline targeted styles...
        },
        [`& ${Tagline}`]: {
          // .. Tagline targeted styles...
        },
      }
    }
  }
});
```

I expected this to work, but realized that the class names generated for Headline and Tagline are the same.  Is there a way to force them to be different so that I can style them from another component?

I know this seems silly, but after doing a ton of different iterations with various systems, this method seemed the cleanest, and internally we agreed.

A hack to get this to work is:

```typescript
const Headline = styled('div', {
    '--headline': true
});

const Tagline = styled('div', {
    '--tagline': true
});
```

**Comment by Kinbaum** [comment]
@j You can add a `toString()` function to your `Headline` and `Tagline`.

```js
const Headline = styled('div');
const Tagline = styled('div');

// This exposes each respective className (`.c-abc123`) for you to use
Headline.toString = () => Headline.selector;
Tagline.toString = () => Headline.selector;

const Container = styled('div', {
  // base styles
  variants: {
    style: {
      box: {
        [`& ${Headline}`]: {
          // .. Headline targeted styles...
        },
        [`& ${Tagline}`]: {
          // .. Tagline targeted styles...
        },
      }
    }
  }
});
```

**Comment by hadihallak** [comment]
Closing in favor of #976
