### ISSUE TITLE
Exported variable "Variable" has or is using name 'Stitches' from external module

### ISSUE THREAD

**Issue by oeduardoal** [stitchesjs/stitches#1014]
After updating to 1.2.8, I'm getting all kinds of Type errors.
https://github.com/modulz/stitches/releases/tag/v1.2.8

```
 Exported variable 'StyledInput' has or is using name 'Stitches' from external module "/Users/oeduardoal/projects/gb/flora-ds/packages/core/dist/types/flora.config" but cannot be named
```

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/12778450/165798128-db4c345d-4b11-49ce-b857-68197936e10d.png">

**Comment by hadihallak** [comment]
Would you mind creating a repo with the issue?
worth trying is to remove node_modules and your lock files

**Comment by oeduardoal** [comment]
@hadihallak Of course! I'll comment here!

**Comment by oeduardoal** [comment]
Hey @hadihallak !

https://github.com/oeduardoal/stitches-issue

it's looks like something with Type in "utils":

Github Actions: https://github.com/oeduardoal/stitches-issue/runs/6258791386?check_suite_focus=true

```tsx
export const designsystem = createStitches({
  prefix: "designsystem-",
  theme: {},
  media: {},
  utils: {
    p: (value: Stitches.PropertyValue<"padding">) => ({
      padding: value,
    }),
  },
});
```

When not used, the error does not occur

**Comment by Kinbaum** [comment]
@oeduardoal Try this instead

```js
import { createStitches, ScaleValue } from '@stitches/react';

export const designsystem = createStitches({
  prefix: "designsystem-",
  theme: {},
  media: {},
  utils: {
    p: (value: ScaleValue<'space'> | string | number) => ({
      padding: value
    })
  }
});
```

**Comment by jrgarciadev** [comment]
Hi guys 🙌🏻 , any update on this?

**Comment by gregogun** [comment]
@oeduardoal @jrgarciadev are you guys importing `* as Stitches` type in your `stitches.config.ts` file? 

removing the type and just importing `ScaleValue` and/or `PropertyValue` from `@stitches/react` solved the issue for me. Hope this might help 👍
