### ISSUE TITLE
[Feature] Allow to override the default global config, to keep importing styled from '@stitches/react' in all files

### ISSUE THREAD

**Issue by caub** [stitchesjs/stitches#1023]
Currently if you need to customize the config (example: https://stitches.dev/docs/responsive-styles), you'll need to change all your

```js
import { styled } from '@stitches/react';
```

into 

```js
import { styled } from 'path/to/your/config';
```

which is annoying, it's easier to spot when stitches is an external import

So I'd propose something like `stitches.config.js`:

```js
import { setGlobalConfig } from'@stitches/react';

setGlobalConfig({
  media: {
    bp1: '(min-width: 640px)',
    bp2: '(min-width: 768px)',
    bp3: '(min-width: 1024px)',
  },
});
```

**Comment by hadihallak** [comment]
@caub Thanks for your suggestion but unfortunately, that's not something we will add to Stitches as the global `styled`, `css` functions were just meant for quick prototyping so the moment you want to modify the config, you should reach for the createStitches function and do it there.
