### ISSUE TITLE
Property 'length' is missing in type ... on TypeScript 4.7+

### ISSUE THREAD

**Issue by ajmnz** [stitchesjs/stitches#1035]
# Bug report

## Describe the bug

#947 is happening again with TypeScript 4.7+.

TypeScript version: 4.7.3
@stitches/react version: 1.2.7

https://user-images.githubusercontent.com/57961822/172218409-014fb5e9-0ddf-4393-8b99-8abdaeefc145.mov

**Comment by hadihallak** [comment]
Does this only happen locally or are you able to repro on a codesandbox?
Would really appreciate if you could share something that I could quickly clone or open such as a codesandbox

**Comment by ajmnz** [comment]
> Does this only happen locally or are you able to repro on a codesandbox? Would really appreciate if you could share something that I could quickly clone or open such as a codesandbox

Never mind, updating to 1.2.8 fixed it!
