### ISSUE TITLE
is Stitches dead?

### ISSUE THREAD

**Issue by fokkerone** [stitchesjs/stitches#1059]
After reading the statement on modulz page and some posts in twitter.
My questions are
- is Stitches dead?
- Any Updates for React18? SSR + static style generation?
- can we back the project to keep it up in production?

Any ideas to move to an alternative (sadly since DX is so far the best for all CSSinJS solutions )

**Comment by hadihallak** [comment]
> is Stitches dead?

No

> Any Updates for React18? SSR + static style generation?

No plans to support this in Stitches as of yet.

> can we back the project to keep it up in production?

it's already in production and we're committed to fixing bugs or issues

if you have more questions feel free to ask them on discord as you're likely to get the answer there quickly as we're trying to keep issues to actual stitches bugs/feature requests
