### ISSUE TITLE
TypeScript issue with PropertyValue and TS v4.8.2

### ISSUE THREAD

**Issue by csantos1113** [stitchesjs/stitches#1078]
# Bug report

## Describe the bug

using `PropertyValue` for defining a custom util in TypeScript 4.8.2 generates the following typescript error:

```
TS4118: The type of this node cannot be serialized because its property '[$$PropertyValue]' cannot be serialized.
```

## To Reproduce

I cannot reproduce this in codesandbox because I can't change the TypeScript version (See: https://github.com/codesandbox/codesandbox-client/issues/942)

1. Create a react server with typescript 4.8.2
2. Create stitches config

```
const stitches = createStitches({
  utils: {
    marginHorizontal: (value: PropertyValue<'margin'>) => ({
      marginLeft: value,
      marginRight: value
    })
  }
});

export const { css, config, createTheme, getCssText, globalCss, keyframes, reset, styled, theme } =
  stitches;
```

3. notice the TS error

## Expected behavior

I should be able to use `PropertyValue` on TS 4.8.2

## Screenshots

<img width="1144" alt="Screen Shot 2022-09-02 at 10 19 26 AM" src="https://user-images.githubusercontent.com/9648559/188182618-350decdb-d47f-4613-9f47-3002a5edc1c0.png">

## System information

- OS: N/A
- Browser: N/A
- Version of Node.js: N/A
- Version of Stitches: 1.2.8
- Version of TypeScript: 4.8.2

**Comment by jackguoAtJogg** [comment]
I'm not sure how many people have this issue experience. I'm on Typescript 4.5.2 and getting the same error, and the error came out from no where.

**Comment by domcoleman** [comment]
> I'm not sure how many people have this issue experience. I'm on Typescript 4.5.2 and getting the same error, and the error came out from no where.

If you're using VS Code you can switch to the workspace version of TypeScript, by default it will use VS Code's version.

<img width="354" alt="Screenshot 2022-09-06 at 10 30 00" src="https://user-images.githubusercontent.com/46578754/188600218-cab2bd55-b451-4474-9a4f-edfc9cb8f85b.png">

**Comment by jackguoAtJogg** [comment]
@domcoleman Thank you! That worked for me 😁

**Comment by gabrieloureiro** [comment]
Any update?

![Screen Shot 2022-09-08 at 09 53 28](https://user-images.githubusercontent.com/39869298/189126790-cb4d57c8-b1b0-4e11-a200-a2bfa18b92c6.png)

**Comment by jakubzet** [comment]
> Any update? The both version of typescript (vsc and node_modules) are reporting this error.
> 
> What is the stable version for stitches?
> 
> ![Screen Shot 2022-09-08 at 09 53 28](https://user-images.githubusercontent.com/39869298/189126790-cb4d57c8-b1b0-4e11-a200-a2bfa18b92c6.png)
> 
> ![Screen Shot 2022-09-08 at 09 54 22](https://user-images.githubusercontent.com/39869298/189126970-35215bc2-32a6-471b-b6e5-4d9ee3983df3.png)

You're using the same TypeScript versions in both cases. The last version of TypeScript which doesn't throw errors is 4.7.4. Find your package.json file and force appropriate TS version, then reinstall packages and select version from node_modules.

**Comment by Andarist** [comment]
Since this has changed between 4.7 and 4.8 - is there any TS issue to track this specific regression/change on their side?

**Comment by dzek69** [comment]
To anyone still using stitches like me, and wanting to upgrade TypeScript, do this:
- install `patch-package` npm package
- create `patches` folder in the same folder you have your `package.json`
- download this file: 
[@stitches+react+1.2.8.zip](https://github.com/stitchesjs/stitches/files/15234724/%40stitches%2Breact%2B1.2.8.zip) and extract the contents into `patches` folder
- in the `prepare` script in `package.json` add `patch-package` command
- `npm run prepare`

All thanks should go to @jgoz (who fixed that) and @gajus (who created a patch file I slightly modifed). I hope did not miss anyone.
