### ISSUE TITLE
Polymorphism for Composing React Components

### ISSUE THREAD

**Issue by Code-Victor** [stitchesjs/stitches#1088]
I need "as"  prop for polymorphism in a styled react component.
I've accessed the styles and variants through the className prop, 
but I don't know if there's a way to get the `as` prop.
```js
const baseButton = ({ onclick, className, children }) => {
  //...
  return <button className={className}>{children}</button>;
};
const Button = styled(baseButton, {
  //styles...
});
```

**Comment by hadihallak** [comment]
Could you please provider a full example of what you're trying to do?

**Comment by Code-Victor** [comment]
I wish to have this sort of functionality.
```jsx
<Button as="a" href="#" >hello</Button>
```

**Comment by hadihallak** [comment]
That's already part of Stitches but if you do that, `baseButton` would be replaced by `a`.

**Comment by hadihallak** [comment]
we have new changes merged with canary that will allow you to control polymorphism using a new [withConfig](https://github.com/stitchesjs/stitches/pull/1103) API but that isn't released yet

**Comment by Code-Victor** [comment]
Thanks so much for the assistance using the "withConfig" API would come in handy in solving the issue 👍
