### ISSUE TITLE
Opacity Token

### ISSUE THREAD

**Issue by diegosilvadigital** [stitchesjs/stitches#1102]
Would it be interesting to support opacity tokens to standardize design systems? something like that:

```jsx
theme: {
  // lineHeights: { ... },
  opacities: {
    'opacity-transparent': 0,
    'opacity-translucent': 0.5,
    'opacity-opaque': 1,
  },
  // radii: { ... },
}
```

**Comment by hadihallak** [comment]
Hey @diegosilvatech 👋  
This is already possible without any changes to Stitches:
https://codesandbox.io/s/opacity-scale-lh19xx?file=/src/App.js

Let me know if you have any other questions

**Comment by diegosilvadigital** [comment]
this is amazing @hadihallak. I hadn't tested it like that. Thanks!

**Comment by hadihallak** [comment]
You're very welcome! glad this solved the issue for you.

**Comment by om-orshee** [comment]
I'm getting : 'DefaultThemeMap' only refers to a type, but is being used as a value here.ts(2693)
when i tried :
  themeMap: { ...DefaultThemeMap, opacity: 'opacities' },
  theme: {...
  
after importing it like :
import { createStitches, DefaultThemeMap } from '@stitches/react';
