### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by csantos1113** [stitchesjs/stitches#1121]
Could we pls cut a stable release with the latest changes from https://github.com/stitchesjs/stitches/compare/v1.2.8...v1.3.1-1 ?

Thanks

**Comment by osvaldokalvaitir** [comment]
I was thinking about changing my projects to stitches, but I saw that it's been almost a year without any changes. Is this library still being maintained?

**Comment by iduuck** [comment]
@osvaldokalvaitir The official statement says "Yes" – but unfortunately, I don't think so anymore.

**Comment by carlosriveroib** [comment]
Sadly, I was falling in love with this project but now I'm switching from stitches to tailwind

**Comment by iduuck** [comment]
Same for me! I am using it in a big project right now, and need to have a look on how to migrate...

**Comment by hipstersmoothie** [comment]
I think either of these are good alternatives:

https://vanilla-extract.style/documentation/packages/recipes/
https://vanilla-extract.style/documentation/packages/sprinkles/

If you use variants => use recipes
Otherwise use sprinkles

**Comment by StephenHaney** [comment]
Please come discuss in #1144
