### ISSUE TITLE
when using prefix, theme tokens in globalCSS aren't prefixed

### ISSUE THREAD

**Issue by flowen** [stitchesjs/stitches#1136]
# Bug report

## Describe the bug

Added a prefix in the stitches config, but when using a design token in the globalCSS function it won't add it

## To Reproduce

```
const { styled, getCssText, keyframes } = createStitches({
  prefix: 'st-', // temp untill we remove styled-comp
  theme: {
    fonts: {
      helvetica: "'Helvetica Neue', sans-serif",
    },
  ...
}})

const globalStyles = globalCss({
  '*': {
    boxSizing: 'border-box',
    fontFamily: '$helvetica',
  },
  ...
});

export { styled, globalStyles }

```

app.js:
```
export default function App({ Component, pageProps }) {
  globalStyles()

  return (
    <React.StrictMode>
         ...
    </React.StrictMode>
  )
}
```

browser:
<img width="308" alt="CleanShot 2023-01-22 at 14 30 40@2x" src="https://user-images.githubusercontent.com/4084169/213921172-f8216b63-57c7-4483-96d1-a3484be2b1f6.png">
<img width="370" alt="CleanShot 2023-01-22 at 14 31 00@2x" src="https://user-images.githubusercontent.com/4084169/213921184-e2201758-16f7-45db-b498-e7eb8fc17b4d.png">

**Comment by Liombe** [comment]
I think it should be working if you export `globalCss` function from your `createStitches` intead of `@stitches/react`, just like you did with the `styled` function.

**Comment by flowen** [comment]
@Liombe TY! that was it indeed
