### ISSUE TITLE
[0.1.0-canary.x] Wrong styles applied when using compound variants in combination with responsive variant prop

### ISSUE THREAD

**Issue by apostolos** [stitchesjs/stitches#386]
Stitches v0.1.0 applies unrelated compound variant combinations to components that have a responsive prop.

Please see the example below to better understand the problem.

## To Reproduce

https://codesandbox.io/s/stitches-responsive-variant-ts-020-dz1hd?file=/src/App.tsx

There are 4 compound combinations:

1. normal / delta
2. normal / echo
3. normal / alpha
4. normal / bravo

There are two buttons:

```jsx
<Button rounding="normal" phonetic={{ initial: "delta", lg: "echo" }}>Button</Button>
<Button rounding="normal" phonetic="delta">Button</Button>
```

Which means that both buttons should have "delta" applied initially, but "echo" should be applied on the first button when condition "lg" is satisfied (viewport > 900px).

However what happens is that css from two unrelated compound variants are applied on the first button (at all breakpoints!):
- normal / alpha
- normal / bravo

This is totally unexpected and should not happen.

Please note that this only happens when compound variants are used. Specifying responsive props in a component with no compound variants works as expected (see 3rd button on codesandbox). No unspecified variants are applied.

**Comment by apostolos** [comment]
Fixed in 0.1.0.canary.14

**Comment by loiacon** [comment]
It's not working in my case yet 😞

Here, I just want padding on `Container` when `color="white"` and `bg="red"`
https://codesandbox.io/s/stitches-conditions-ts-fidkp

**Comment by apostolos** [comment]
@loiacon You are right, it's only partially fixed. It no longer applies unrelated variants, that part is fixed, however styles from the initial `compoundVariant` persist when other combinations are applied.

#432 was not a duplicate after all. I thought it was part of the same bug. Sorry!

@peduarte @jonathantneal Should I keep this open or close it in favor of #432 ?

**Comment by apostolos** [comment]
I've updated the original codesandbox to also reproduce the bug:
https://codesandbox.io/s/stitches-responsive-variant-ts-8qez0?file=/src/App.tsx

(The first button should not have italic text in viewports > 900px)

**Comment by hadihallak** [comment]
@apostolos Doing some house keeping for stitches and by looking at this issue, This is actually working as intended because of how media queries work in css.

if you want to avoid this issue, I would recommend you use the css range syntax to define you media queries **without overlap**
```js
import { createStitches } from "@stitches/react";

export const { styled } = createStitches({
  media: {
    phone: "(width < 720px)",
    tablet: "(720px <= width < 1024px)",
    desktop: "(1024px <= width < 1536px)",
    wide: "(1536px <= width)",
  },
});
```

Please feel free to re-open the issue if I misunderstood your issue.
