### ISSUE TITLE
Make getCssString work with custom theme

### ISSUE THREAD

**Issue by AndrewPrifer** [stitchesjs/stitches#738]
**Is your feature request related to a problem? Please describe.**
I am trying to server-side render a custom theme, but it seems like getCssString only renders the default css vars.

**Describe the solution you'd like**
Stitches could pick up on custom themes created just like it does with calls to the `css` function, and render that theme out as well. Then I could just make sure that I attach the correct classname to the body at SSR.

**Comment by peduarte** [comment]
Checking in on this. Can it be closed?

**Comment by AndrewPrifer** [comment]
Oh I completely missed your answer @jonathantneal, thanks a ton!

@peduarte I would never have expected this to be the solution to what I see as quite a normal use case, the behavior here doesn't really seem intentional haha. Although my problem specifically is solved, do you think this use case could be better supported, through documentation, and (ideally, I think) a more explicit API?

**Comment by peduarte** [comment]
Totally. Appreciate the suggestion!

**Comment by hadihallak** [comment]
Closing the issue as it's solved by https://github.com/stitchesjs/stitches/issues/738#issuecomment-916097289
