### ISSUE TITLE
"reset" function returned from createStitches missing in docs

### ISSUE THREAD

**Issue by lukemorales** [stitchesjs/stitches#782]
# Bug report

## Describe the bug

As you can see in the screenshot, `createStitches` also returns a `reset` function but the docs (screenshot 2) does not have it to explain what it does exactly.

So basically 2 points in this issue:
1. Need to add the reset function to the docs;
2. What does `reset` actually do?

## Screenshots

![CleanShot 2021-09-15 at 00 51 31](https://user-images.githubusercontent.com/14251143/133367886-c41a296c-f774-468d-9461-e24564f5184f.png)
![CleanShot 2021-09-15 at 00 52 51](https://user-images.githubusercontent.com/14251143/133367972-a8e72825-f5ef-4b40-ac8d-75d4c2798773.png)

**Comment by peduarte** [comment]
It's not missing in the docs, it has been left out on purpose. It's more of an internal function. It's there for rare cases where users need to completely empty the inject styles.

I think 99% of users won't need it, so my idea was to leave it out, for simplicity.

I could add it to the API Page though I guess 🤔

**Comment by lukemorales** [comment]
I think it's good information to have in the docs, especially if this attends a unique use case. I was thinking it might be a CSS reset function that removed all browser styles, but wasn't sure of its purpose
