### ISSUE TITLE
Stitches throwing exceptions "TypeError - Converting circular structure to JSON"

### ISSUE THREAD

**Issue by YuvalZiegler** [stitchesjs/stitches#832]
# Bug report

We use stitches at [attentive](https://www.attentivemobile.com) to power our internal component library and style system, we love it, so first off, thank you! Part of what we do at attentive is render UI on our clients' sites, we recently switched to using our new internal library, powered by stitches, and ran into this circular dependency issue.

## Describe the bug

When any circular dependency exists in the document, `createStitches` fails

## To Reproduce

I've created a code sandbox that reproduces the issue here: https://codesandbox.io/s/circular-json-reproduction-0i5lp?file=/src/App.tsx

to reproduce locally:

```js
document.someLib = {};
document.someLib.ref = someLib;

const { styled } = createStitches({});
// ^ throws  "TypeError - Converting circular structure to JSON"
```
## Expected behavior

Should be able to handle circular JSON

## Screenshots

with a circular dep: 

<img width="1421" alt="Screen Shot 2021-10-06 at 10 36 24 AM" src="https://user-images.githubusercontent.com/248544/136224971-acfc6690-38f0-4b75-a898-923170cb46c9.png">

without

<img width="915" alt="Screen Shot 2021-10-06 at 10 37 35 AM" src="https://user-images.githubusercontent.com/248544/136225188-6d8bb938-6b2e-4217-b104-397b1168ed66.png">

## System information

- OS: macOS (but will affect all)
- Browser: All
- Version of Stitches: 1.2.3

## Note

Related to this issue was recently closed: https://github.com/modulz/stitches/issues/665#issue-941848074

**Comment by peduarte** [comment]
Hey, I created a PR (https://github.com/modulz/stitches/pull/836) 

I've forked your sandbox, and updated the dependency to use the build from that PR.

Here's a sandbox: https://codesandbox.io/s/circular-json-reproduction-forked-w3cr5?file=/package.json

Looks like that fixes the problem

**Comment by YuvalZiegler** [comment]
this is great! thanks for the fast fix!
