### ISSUE TITLE
No TS linting error is displayed when a css key (e.g. 'color') or a token value (e.g. '$primary') is misspelled

### ISSUE THREAD

**Issue by willdspd** [stitchesjs/stitches#838]
In the style object provided to the styled or css functions, no TS error is thrown when a css key (e.g. 'colorr') or a theme token value (e.g. '$pprimary') is misspelled.

As evidenced [here](https://codesandbox.io/s/stitches-003-canary1-forked-fqvfs?file=/src/App.tsx), this used to work correctly. I believe this was by adding 'strict: true' to the config object, however, nothing related to this setting appears to be in the docs.

To reproduce, use @stitches/react (version: 1.2.1) with Next.js.

- OS: macOS
- Stitches version: 1.2.1
- Next.js version: 11.1.0

**Comment by williamdespard** [comment]
Hi, thanks for your reply. Unfortunately, relying on the theme object prevents two things:

**Comment by kylemh** [comment]
@williamdespard I think you can close this and watch #858
