### ISSUE TITLE
className removed after styling component

### ISSUE THREAD

**Issue by LucasCaixeta** [stitchesjs/stitches#857]
# Bug report

## Describe the bug

Component with class name, after imported in other component and changed the styling, do not show the classname added before.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- Create a simple component and add <FirstComponent className="something" ...etc
- Create another component that will use the previous and customise it: 

```
export const StyledFirstComponent = styled(FirstComponent, {
  display: 'flex',
});
```

Now, in the SecondComponent's tests, if we see in the "StyledFirstComponent", the className added before styling is not there anymore.

## Expected behavior

Have the previous className added in the component before extending it in the styling.

## Screenshots

console.log the "FirstComponent", has the icon-Success class:
![image](https://user-images.githubusercontent.com/408965/138675043-a32497b3-9ebf-4e22-a649-eee976953ac8.png)

console.log the "StyledFirstComponent", has not the icon-Success class:
![image](https://user-images.githubusercontent.com/408965/138675163-bcc45ef4-2992-4cad-9cea-dbfb4262e618.png)

## System information

- OS: Mac
- Browser (if applies):  Chrome
- Version of Stitches: [1.2.5]
- Version of Node.js: [14.18.1]
- Version of NPM: [8.1.1]

## Additional context

- problem found by @filipa.marta@gmail.com

**Comment by caub** [comment]
Confirmed, and it happens only with server-side rendering

**Comment by caub** [comment]
You probably forgot to pass the `className` prop, can you make a repro on codesandbox.com or repl.it?

**Comment by hadihallak** [comment]
@LucasCaixeta I believe that what @caub mentioned is probably the cause of your issue. Could you please create a repro of the issue on codesandbox?

**Comment by LucasCaixeta** [comment]
Hi there @hadihallak , thank you for your message.
I moved to another job and I have no access to the code to reproduce the bug.

Should I close it?

Thanks anyways.
