### ISSUE TITLE
Css classes of the variants not following the order that they are set

### ISSUE THREAD

**Issue by giofreitas** [stitchesjs/stitches#883]
# Bug report

I have this component with following variants:
```
  variants: {
    size: {
      small: {
        fontSize: "$16",
        height: "2rem"
      },
      medium: {
        fontSize: "$18",
        height: "2.5rem"
      },
      large: {
        fontSize: "$20",
        height: "3rem"
      }
    },

    ...

    isUpperCase: {
      true: {
        textTransform: "uppercase",
        fontSize: "$14"
      }
    },
```
which end up generating the css in a different order:
```
 .c-wbjmB-gBjoZX-size-large {
  font-size:var(--fontSizes-18);
  height:3rem
 }

 ... 

 .c-wbjmB-fkTsxy-isUpperCase-true {
  text-transform:uppercase;
  font-size:var(--fontSizes-14)
 }

 ...
 
 .c-wbjmB-cUMHCW-size-medium {
  font-size:var(--fontSizes-18);
  height:2.5rem
 }
 .c-wbjmB-byBxHz-size-small {
  font-size:var(--fontSizes-16);
  height:2.125rem
 }
```
So if I set the component to be uppercase and medium (or small) size, the font-size value does not get overridden by `.c-wbjmB-fkTsxy-isUpperCase-true` cause it does not come after

## Expected behavior

I would expect the generated css to follow the order of the variants since its common practice in css to rely on the order of the rules to establish a logic when it comes to override rules

## System information

- OS: Windows
- Version of Stitches:"@stitches/react": "^1.2.5"
- Version of Node.js: 15.12.0

**Comment by peduarte** [comment]
Hey, do you have a reproduction of this? Injection order is based on usage, and not how it was written. We've been making some changes to how the CSS is injected though, @hadihallak can provide more context. Thanks!

**Comment by peduarte** [comment]
Can you try Stitches 1.2.6?

**Comment by hadihallak** [comment]
@peduarte is correct, However, I don't believe this is changed/fixed in `1.2.6`

**Comment by giofreitas** [comment]
@peduarte ok I see. I will try to build a simple example of this. I'm not even sure if this could be classified as bug. Do you think this is something that should be changed/fixed? Right now, my workaround is to use compound variants with just the `isUpperCase` variant:
```
  compoundVariants: [
  
    ...
  
    {
      isUpperCase: true,
      css: {
        fontSize: "$14"
      }
    },
    
    ...
``` 
I know this is not what compound variants is meant for but seems to do the job.

**Comment by peduarte** [comment]
@giofreitas we'll investigate, but I think your current workaround is fine for now, as compound variants are guaranteed to be injected later
