### ISSUE TITLE
Style injection order is wrong 

### ISSUE THREAD

**Issue by dirkjf** [stitchesjs/stitches#906]
# Bug report

## Describe the bug

Style injection order will sometimes change, seemingly out of the blue. This is problematic when CSS selectors have the same specificity. For example: 
```
const Wrapper = styled("div", {
  "> * + * ": {
    marginTop: "8rem"
  }
});

const Child = styled("div", {
  marginTop: "0"
});

export default function App() {
  return (
    <Wrapper>
      <Child>Child</Child>
      <Child>Child</Child>
    </Wrapper>
  );
}
```
I would expect the children to always have a top margin of 0, but sometimes, this is not the case. It seems like it depends on which component was last edited, but there are also times I cannot reproduce the issue. 

## To Reproduce

1. Visit https://codesandbox.io/s/objective-merkle-ituzz?file=/src/App.tsx
2. Add a line for the Wrapper component, for example: `color: "red",`

You will now see the second child has received the top margin, because the Wrapper CSS is loaded after the Child CSS. 

## Expected behavior

Styles of a "deeper" (ie: child) component, should be injected after wrapper (or parent) components, always. 

## Screenshots
![image](https://user-images.githubusercontent.com/34198573/146804640-e886db2f-1e56-491f-9895-d081c402e1bf.png)

## System information

- Version of Stitches: 1.2.6

**Comment by hadihallak** [comment]
Closing as this was fixed in https://github.com/stitchesjs/stitches/pull/875
