### ISSUE TITLE
unordered "media" styles generation

### ISSUE THREAD

**Issue by vitordino** [stitchesjs/stitches#917]
## Summary
> tl;dr: follow the order of declaration on the config when generating media-bound styles (maybe even at top level)

although some [might suggest](https://github.com/modulz/stitches/issues/901) not to have overlaps on media/breakpoints, i do find it confusing/breaking some web standards and best practices — for example mobile-first media queries usually just use `min-width` instead of a range (as it’s on stitches website)

## To Reproduce

here’s a scenario where i’m having a hard time making it work:

```tsx
media: {
  xs: '(min-width: 0px)',
  sm: '(min-width: 576px)',
  md: '(min-width: 768px)',
  lg: '(min-width: 992px)',
  xl: '(min-width: 1280px)',
}
```

> also tried naming alphabetically, like bp1 – bp5, to no avail

[codesandbox](https://codesandbox.io/s/stitches-media-order-output-pwibo)

look how we have some completely mixed media-query overrides: `576px` → `0px` → `768px`
![Screen Shot 2022-01-05 at 4 30 36 AM](https://user-images.githubusercontent.com/5063967/148177787-f4721547-061e-4819-bca9-74215155d789.png)

this should be a way simpler a version of [my website](https://vitordino.com)’s [grid overlay component](https://github.com/vitordino/vitordino.com/blob/master/src/components/GridOverlay/index.js) (you can visit the site and right click the 🌞 🌔 button to show it)

## Expected behavior

the styles would be output following the order i’ve written (`0px` → `576px` → `768px` on the aforementioned scenario)

## System information

- OS: macOS
- Browser (if applies) chrome, safari and firefox
- Version of Stitches: `@stitches/react@1.2.6`
- Version of Node.js: `v14.18.2`

**Comment by joshuaellis** [comment]
As a work around I found using the `bp1` etc. rule did work for me, but what was bewildering was the breakpoint at `1600` didn't even exist?

**Comment by vitordino** [comment]
for me it didn’t @joshuaellis 😢

**Comment by seedy** [comment]
:information_source: My suggestion was more of a workaround to have something working @vitordino. I closed the related issue because it makes no sense.

I'm waiting for reactions from stitches team there, as the issue has been sitting there for a while.

Any updates on your side?

**Comment by hadihallak** [comment]
yes this is something on the radar but gonna take some time of as it's a bit of an involved change that needs tons of testing
