### ISSUE TITLE
[FR] Static Extraction

### ISSUE THREAD

**Issue by joshuabaker** [stitchesjs/stitches#955]
It’s been mentioned a couple times in issue comments (#760, #863), but there’s currently no explicit feature request for static extraction.

The ideal outcome of any related changes here would be to export a stylesheet (like [`vanilla-extract`](https://github.com/seek-oss/vanilla-extract#readme)) that can be imported with the associated component(s).

**Comment by jimzer** [comment]
Great to see this. Can't wait to move my app on Next 12/React 18 😁

**Comment by jimzer** [comment]
Hi guys :) 
Do you have any news on this feature? 

Thanks again for this awesome styling library!

**Comment by drianoaz** [comment]
[Modulz has been acquired by WorkOS](https://modulz.app/blog/modulz-acquired-by-workos). In the announcement there is the following explanation about this:

> We don’t have plans to introduce static extraction right now, but Stitches remains a great styling solution for dynamic web apps targeting desktop users primarily.

Since the acquisition of Modulz, I feel that the project is gradually being abandoned. 😢 

I really like Stitches and would like to continue using it in my projects, but I don't feel sure about the future of the project.

**Comment by coopbri** [comment]
> [Modulz has been acquired by WorkOS](https://modulz.app/blog/modulz-acquired-by-workos). In the announcement there is the following explanation about this:
> 
> > We don’t have plans to introduce static extraction right now, but Stitches remains a great styling solution for dynamic web apps targeting desktop users primarily.
> 
> Since the acquisition of Modulz, I feel that the project is gradually being abandoned. cry
> 
> I really like Stitches and would like to continue using it in my projects, but I don't feel sure about the future of the project.

Thanks for sharing this! Do you have any recommendations for alternatives to migrate to? Perhaps `vanilla-extract` (as discussed in OP) or an open-source `stylex` alternative such as https://github.com/johanholmerin/style9? I am currently using Chakra but am on the lookout for a framework with static extraction.

**Comment by drianoaz** [comment]
Are there any plans to reconsider adding of Static CSS Extraction?

This might be a good way to support React 18 Streaming SSR https://github.com/stitchesjs/stitches/issues/1109

**Comment by joshuabaker** [comment]
I’m tempted to close this issue as I don’t think it’s going to be reconsidered.

There’s a number of potential alternatives to consider now…

### StyleX
With recent layoffs and moves, I can imagine an open source library being a less attractive for engineers seeking impact. [Naman](https://indieweb.social/@nmn) still has StyleX listed on his bio. 🤞🏻 

### Vanilla Extract
A good option that we’ve used for components in a couple of public design system libraries. There are some constraints that would be addressed by StyleX’s approach (e.g. splitting, injecting for web components, etc.).

### Chakra UI
This remains popular in the team for most applications right now. Segun posted [an update](https://github.com/chakra-ui/chakra-ui/issues/7180) on their progress with static extraction late last year.

> Regarding CSS-in-JS, we've been in a 10-months long research phase to design our first static solution for Chakra UI. We've made a lot of progress with this, and we're excited to show it in the coming months

**Comment by drianoaz** [comment]
Related: https://github.com/stitchesjs/stitches/issues/1144

**Comment by joshuabaker** [comment]
As Stitches is officially [no longer actively maintained](https://stitches.dev/#:~:text=Stitches%20is%20no%20longer%20maintained), I’m going to close this as unplanned. Hoping that this doesn’t ruffle any feathers.

Please see @StephenHaney’s [comment](https://github.com/stitchesjs/stitches/discussions/1149#:~:text=https%3A//vanilla%2Dextract.style/documentation/api/style%2Dvariants/%0Ahttps%3A//panda%2Dcss.com/docs/concepts/recipes%0Ahttps%3A//cva.style/docs) for details and alternative solutions for those wanting static extraction. Others have been good about contributing suggestions in that [discussion](https://github.com/stitchesjs/stitches/discussions/1149?sort=new) too.

Whilst the underlying extraction from others _could_ be used in Stitches, other solutions with active development are far more likely to keep pace with the ecosystem and other evolving standards (e.g. [W3C Token Format](https://tr.designtokens.org/format/)).

We’ve successfully moved large-scale projects over to [Vanilla Extract](https://vanilla-extract.style/) and [Chakra UI](https://chakra-ui.com/), and have opted for [Tailwind](https://tailwindcss.com/) in most new projects.
