### ISSUE TITLE
Theming Question

### ISSUE THREAD

**Issue by ryanhmaas** [stitchesjs/stitches#975]
# Bug report
Accessing theme details

## Describe the bug

Hi all. I'm working on demo-ing two of our themes inside Storybook. I've created two themes, e.g.

```
export const darkTheme = createTheme('dark-theme', {
  colors: darkThemePalette,
});

export const lightTheme = createTheme('light-theme', {
  colors: lightThemePalette,
});
```

I then have a component that consumes them (direct import of those) in a Storybook document, e.g. 

```
### Light Theme 

<ThemePalette theme={lightTheme} />

### Dark Theme

<ThemePalette theme={darkTheme} />
```

```
export default function ThemePalette(theme) {
  console.log(theme);
  return (
    <div className={theme}>
      
    </div>
  );
};
```

When I pass the `theme` to a `div`, nothing seems to be applied. I did some logging and it looks like that object has a `theme` subobject. Are my assumptions (I'm using [this](https://stitches.dev/docs/theming#theme-specific-styles) as a basis) off? Or is my usage incorrect?  FWIW, I just intend to do some variant styling in the `ThemePalette` component based on the theme's class. 

It's not a deal breaker if I just have to do `theme.theme`, but it feels a tad awkward.

## To Reproduce

See above description.

## Expected behavior

I'd expect the class name to be applied like the docs mention.

## Screenshots

![image](https://user-images.githubusercontent.com/5385146/156609097-9cd92537-0a92-4dd3-8621-c924fe68ce28.png)
![image](https://user-images.githubusercontent.com/5385146/156609174-23a38715-c74d-41af-98d7-a3aae258108d.png)

## System information

- OS: Windows
- Browser (if applies): Chrome
- Version of Stitches: We're using the React package @1.2.6
- Version of Node.js: 16.13.0

**Comment by navaru** [comment]
```
