### ISSUE TITLE
If using disabled variant it will not prevent onClick from firing

### ISSUE THREAD

**Issue by jonasthiesen** [stitchesjs/stitches#977]
# Bug report

## Describe the bug

When you use the `disabled` variant on a button, the `onClick` will fire. If you don't add this variant, it will prevent the `onClick` from firing as expected.

```tsx
const ButtonDisabledVariant = styled("button", {
  variants: {
    disabled: {
      true: {
        opacity: 0.5
      }
    }
  }
});
```

## To Reproduce

This example has two buttons, one with the `disabled` variant and one without to illustrate:
https://codesandbox.io/s/gallant-sky-up4h1s

## Expected behavior

I expect the `onClick` handler to not fire when when it's disabled even when I'm adding `disabled` as a variant.

## System information

- OS: macOS
- Browser: Firefox, Safari, Chrome
- Version of Stitches: 1.2.7
- Version of Node.js: 16.8.0

## Additional context

I suspect this might happen because the `disabled` part of the button will be completely replaced with stitches own implementation?

**Comment by emdowu** [comment]
just use
> pointerEvents: none

on disabled props

**Comment by jonasthiesen** [comment]
Interesting, that actually works. Didn't expect this to be solvable using just CSS. I think I would still expect it to do this by default considering that's the default behavior of the button, but maybe there's more to it below the surface.

**Comment by rothsandro** [comment]
`pointerEvents` only works for clicks but does not really disable the button. It will still be enabled and "clickable" for keyboard users and screen readers.

You can remove the disabled variant and use "&:disabled" to style a disabled button. This will add the `disabled` attribute on the button and correctly disable it.

**Comment by jonasthiesen** [comment]
Yeah, should probably have though of that actually. I guess I would personally still expect the above to not override that default. But maybe that's just me :)

**Comment by paul-sachs** [comment]
Another possibility is to use something like:

```tsx
const ButtonDisabledVariant = styled("button", {
  "&[disabled]": {
    opacity: 0.5
  }
});
```

**Comment by hadihallak** [comment]
we don't forward variant values to the underlying DOM elements and because of that, when setting a variant `disabled` and then use it, your component would prevent it from appearing on the DOM and in return it would not be disabled.

I would suggest that you follow the example @paul-sachs provided
